# Site settings
title: Xmartlabs Blog
email: getintouch@xmartlabs.com
address: Dr Mario Cassinoni 1011 - 11200
phone_eeuu: +16506141829
phone_uruguay: (+598) 2408 7915
description: > # this means to ignore newlines until "baseurl:"
  Articles by Xmartlabs, sharing the knowledge about full-stack mobile design and development in iOS, Android and Ruby.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://xmartlabs.com" # the base hostname & protocol for your site
url_team: "https://xmartlabs.com/#our_team"
url_blog: "https://blog.xmartlabs.com"
twitter_username: xmartlabs
github_username: xmartlabs

# Build settings
markdown: kramdown
future: false
timezone: America/Montevideo
permalink: /:year/:month/:day/:title/

# sass:
#   style: :compressed

defaults:
  # Specify default pages’ layout
  -
    scope:
      path: "_posts/martin"
      type: "posts"
    values:
      author: "mtnBarreto"

jekyll_admin:
  hidden_links:
    - pages
    - staticfiles
    - datafiles
    - configuration


backend:
  name: git-gateway
  branch: master
media_folder: "images"
collections:
  post:
    label: "Post" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}